parameters:
  sow_translation.attribute_class_name: SOW\TranslationBundle\Attribute\Translation
  sow_translation.translation_class_name: SOW\TranslationBundle\Entity\Translation
  sow_translation.translation_method: annotation

  sow_translation.available_locales: [ 'en', 'fr', 'es', 'de', 'it' ]

services:
  sow_translation.translation_repository:
    class: SOW\TranslationBundle\Repository\TranslationRepository
    public: false
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%sow_translation.translation_class_name%"

  sow_translation.attribute_class_loader:
    class: SOW\TranslationBundle\Loader\AttributeClassLoader
    public: false
    arguments:
      - "%sow_translation.attribute_class_name%"

  sow_translation.translation_service:
    class: SOW\TranslationBundle\Service\TranslationService
    public: true
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@sow_translation.translation_repository"
      - "%sow_translation.translation_class_name%"
      - "%sow_translation.available_locales%"

  sow_translation.translator:
    class: SOW\TranslationBundle\Translator
    public: true
    arguments:
      - "@sow_translation.translation_service"
      - "@sow_translation.attribute_class_loader"
      - "%sow_translation.available_locales%"
      - "%sow_translation.translation_method%"
      - "@logger"
